# --- 模型配置 ---
# 注意：api_key_env 对应 .env 文件中的变量名
# base_url 对应模型的 API 地址

models:
  doubao:
    name: "豆包"
    model: "doubao-seed-1-6-flash-250828"
    api_key_env: "DOUBAO_API_KEY"
    base_url: "https://ark.cn-beijing.volces.com/api/v3" # 修正：OpenAI 兼容接口通常只需要到 /v3
    api_type: "openai"

  qwen:
    name: "通义千问"
    model: "qwen-plus" # 使用您提供的模型名称
    api_key_env: "QWEN_API_KEY"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1" # 阿里云兼容模式 URL
    api_type: "dashscope"
    enable_search: true

  deepseek:
    name: "DeepSeek"
    model: "deepseek-v3.2" # 使用您提供的模型名称
    api_key_env: "DEEPSEEK_API_KEY"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1" # 阿里云兼容模式 URL
    api_type: "dashscope"
    enable_search: true

  kimi:
    name: "Kimi"
    api_key_env: "KIMI_API_KEY"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    model: "Moonshot-Kimi-K2-Instruct"
    api_type: "dashscope"
    enable_search: true

  zhipu:
    name: "智谱 GLM"
    model: "glm-4.5-air" # 使用您提供的模型名称
    api_key_env: "ZHIPU_API_KEY"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1" # 阿里云兼容模式 URL2
    api_type: "dashscope"
    enable_search: false
    stream: true

#  zhinao:
#    name: "智脑"
#    model: "360zhinao-turbo"
#    api_key_env: "ZHINAO_API_KEY"
#    base_url: "https://api.360.cn/v1"
#    api_type: "openai"

    #  ernie:
    #    name: "文心一言"
    #    api_key_env: "ERNIE_API_KEY"
    #    secret_key_env: "ERNIE_SECRET_KEY"
    #    #model: "ERNIE-Speed-128K"
    #    model: "ernie-3.5-8k"
    #    base_url: "https://qianfan.baidubce.com/v2"

    # --- 需要单独适配的模型 ---
  hunyuan:
    name: "腾讯混元"
    model: "hunyuan-lite"
    api_key_env: "HUNYUAN_API_KEY"
    secret_key_env: "HUNYUAN_SECRET_KEY" # 新增 Secret Key 字段
    base_url: "https://api.hunyuan.cloud.tencent.com/v1"
    api_type: "openai"

#  spark:
#    name: "科大讯飞星火"
#    model: "lite"
#    api_key_env: "SPARK_API_KEY"
#    secret_key_env: "SPARK_SECRET_KEY" # 新增 Secret Key 字段
#    app_id_env: "SPARK_APP_ID" # 新增 App ID 字段
#    base_url: "wss://spark-api.xf-yun.com/v1.1/chat" # 星火需要一个 Base URL ，但调用方式不同
#    api_type: "spark"


# --- 文件路径配置 ---
paths:
  questions_file: "question/questions_all.json"
  brand_dictionary_file: "config/brand_dictionary_domestic.yaml"
  results_dir: "results"
  merged_results_file: "merged_results/results_merged_domestic.json"
  ranking_output_file: "report/ranking_report_domestic.md"

